version: '3.9'

services:
  postgres:
    image: postgres:17.4-alpine
    platform: linux/amd64
    container_name: todo-postgres-db
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password
      POSTGRES_DB: todo_db_v2
      # Configuración adicional para PostgreSQL
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
      TZ: America/Mexico_City
    ports:
      - "5433:5432"
    volumes:
      - postgres-data2:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todo_user -d todo_db_v2"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  todo-back-app:
    image: todo-back-app-2025:latest
    container_name: todo-back-app
    environment:
        # Configuración de base de datos
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/todo_db_v2
        SPRING_DATASOURCE_USERNAME: todo_user
        SPRING_DATASOURCE_PASSWORD: todo_password
        SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
        
        # Configuración de JPA/Hibernate
        SPRING_JPA_HIBERNATE_DDL_AUTO: update
        #SPRING_JPA_SHOW_SQL: false
        #SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: true
        SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
        
        # Configuración del servidor
        SERVER_PORT: 8080
        
        # Optimización de JVM para contenedor
        JAVA_OPTS: >-
          -XX:+UseContainerSupport
          -XX:MaxRAMPercentage=75.0
          -XX:InitialRAMPercentage=50.0
          -Djava.security.egd=file:/dev/./urandom
    ports:
      - "8080:8080"


volumes: 
  postgres-data2: